version: '3'
services:
  web:
    container_name: nginx
    image: nginx
    volumes:
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf'
      - './src/:/var/www/html'
    ports:
      - '80:80'
    depends_on:
      - php
      - db
  php:
    container_name: php
    build: docker
    volumes:
      - './docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini'
      - './docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini'
      - './src/:/var/www/html'
  composer:
    container_name: composer
    image: composer
    volumes:
      - './src/:/app'
    command: install --no-dev
  db:
    container_name: db
    image: 'postgres:10.12'
    environment:
      - 'POSTGRES_DB=${DB_NAME}'
      - 'POSTGRES_USER=${DB_USER}'
      - 'POSTGRES_PASSWORD=${DB_PASSWORD}'
    ports:
      - '5432:5432'
    volumes:
      - './docker/postgres/data:/var/lib/postgresql/data'
      - './docker/postgres/:/docker-entrypoint-initdb.d/'
