version: '3'

services:
  web:
    container_name: heroes_nginx
    image: nginx
    volumes:
      - './.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf'
      - './src/:/var/www/html'
    ports:
      - '80:80'
    depends_on:
      - php
      - db
  php:
    container_name: heroes_php
    build: .docker/php
    volumes:
      - './.docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini'
      - './.docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini'
      - './src/:/var/www/html'
  composer:
    container_name: heroes_composer
    image: composer
    volumes:
      - './src/:/app'
    command: install --no-dev
  db:
    container_name: heroes_db
    image: 'postgres:10.12'
    environment:
      - 'POSTGRES_DB=${DB_NAME}'
      - 'POSTGRES_USER=${DB_USER}'
      - 'POSTGRES_PASSWORD=${DB_PASSWORD}'
    ports:
      - '5432:5432'
    volumes:
      - './.docker/postgres:/var/lib/postgresql/data'
      - './.docker/postgres:/docker-entrypoint-initdb.d'
  mongo:
    container_name: heroes_mongo
    build: .docker/mongo
    ports:
      - '27017:27017'
    volumes:
      - './.docker/mongo/data:/data/db'
      - './.docker/mongo/mongo_config:/data/configdb'