export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_CHECK = 'AUTH_CHECK';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const BLOG_LIST= 'BLOG_LIST';
export const BLOG_INNER= 'BLOG_INNER';

export const CATEGORIES_LIST= 'CATEGORIES_LIST';
export const CATEGORIES_SHORT_LIST= 'CATEGORIES_SHORT_LIST';
export const CATEGORIES_INNER= 'CATEGORIES_INNER';
